### ISSUE TITLE
live lockscreen

### ISSUE THREAD

**Issue by ghost** [holmeslinux/Manjaro-JWM#11]
Hi,
 I installed and walked away, and now there is a lockscreen (which is very confusing at first).  I do not know the password.... what is it

**Comment by holmeslinux** [comment]
hello mate
in the Manjaro JWM i use the i3lock for lockscreen and the password in the live session is manjaro and the user is manjaro.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
new isso, see

https://forum.manjaro.org/t/test-manjaro-jwm-oncremmer-17-01rc-code-28117/16551

vlw fwi, Holmes :)
