### ISSUE TITLE
Add a default tool for handling multiple keyboard layouts.

### ISSUE THREAD

**Issue by adderly** [holmeslinux/Manjaro-JWM#6]
It would be nice to have a utility to handle multiple layouts. 
For example something like https://aur.archlinux.org/packages/jbxkb .

**Comment by holmeslinux** [comment]
hi adderly, the idea of the Manjaro JWM is not adding anything of the aur in media. is user that must add packages of the aur.

vlw fwi, Holmes :)

**Comment by adderly** [comment]
Ok, i get it. 
I thought you wanted to get something somewhat geared up from the time of install. Those little tools just make the hustle of configuration a little less painful.
I guess i misunderstood the goal here.  
;)
