### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by n-a-m-e** [holmeslinux/Manjaro-JWM#7]
Hi,
I'm slowly working on creating a antergos jwm configuration so that hopefully even more people start using jwm 😄 anyways I've been doing a lot of research trying to create the ultimate setup and I thought I'd let you know some of the stuff I found out.

1.
I've tried all the jwm menu generators and the best one is is called [mjwm](https://github.com/chiku/mjwm) all you have to do is add:

```
  <RootMenu onroot="12">
      <!-- Other Menu Entries -->

      <Include>$HOME/.jwmrc-mjwm</Include>

      <!-- Other Menu Entries -->
  </RootMenu>
```

and then run 
`mjwm && jwm -reload`
after a new program is installed or removed and all your menus are update automagically 😃 
or you can add a menu button like
`<Program icon="system-restart.svg" label="Reload Menu">mjwm && jwm -reload</Program>`
and let the user reload the menu whenever they want.

2.
The arch wiki on [prelink](https://wiki.archlinux.org/index.php/Prelink) seems to advise against using it.

3.
There seems to be a promising currently being developed project to create a [JWM Settings Manager](https://launchpad.net/jwm-settings-manager) to allow users to edit jwm without editing any xml files. The maintainers contact details appear in the Revision ID on this [page](https://bazaar.launchpad.net/~israeldahl/jwm-settings-manager/trunk/files) you may want to get in touch with him about the project status and including it in Manjaro-JWM

P.S. Hope you are enjoying the aerosnap feature from v2.3.6. that was me 😃 If you want I will keep you informed of any other discoveries I make on my journey.

**Comment by holmeslinux** [comment]
hello, how are you!
i'm happy with the growth of JWM.
i'm also happy the possibility of having a Antergos with JWM.
perhaps i will leave the Manjaro JWM project.
i'm in problems with the graphical installer (Calamares) and can not solve.
interesting menu manager.
but always i liked to let the user edit the menu.
always i used the prelink and never had any problems.
the maintainer of JWM Settings Manager is Israel.
i know he is the maintainer of the ToriOS.
i need to see the aerosnap and we will talk.

vlw fwi, Holmes :)
