### ISSUE TITLE
JWMConf option to edit Conky is pointing to the wrong file.

### ISSUE THREAD

**Issue by ghost** [holmeslinux/Manjaro-JWM#8]
Hello Holmes, I was trying to edit the default Conky configuration file, looking for change my wireless network interface name, when I selected the option 15 (Edit Conky) inside JWMConf it opened nano editor pointing to /home/%USER/.conkyrc, but actually the place where this file resides by default is /home/$USER/.conky/conkyrc_all or /home/$USER/.conky/conkyrc_key, there are two Conky process running. I think you should substitute the default place where this configuration file resides to /home/$USER/.conky/conkyrc_all inside the JWMConf, that is the main Conky, the other one is just to illustrate the keyboard shortcuts.

I created a pull request with a reasonable fix for this problem: https://github.com/holmeslinux/Manjaro-JWM/pull/9
Please take a look at it.

**Comment by holmeslinux** [comment]
thank you for the warning @chmercesmoreira 
has passed and i have done the fix!

vlw fwi, Holmes :)

**Comment by ghost** [comment]
Thank you, I started using officially this community edition of Manjaro. I'll try to help you if I find other problems. 👍

**Comment by holmeslinux** [comment]
thank youuuuuuuuuuuuuuuu

vlw fwi, Holmes :)
